[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = 'source ~/.config/nvim/bundles/plugins/denite_settings.vim'

[[plugins]]
repo = 'lighttiger2505/gtags.vim'
hook_add = '''
    " Options
    let g:Gtags_Auto_Map = 0
    let g:Gtags_OpenQuickfixWindow = 1
    " Keymap
    " Show definetion of function cousor word on quickfix
    nmap <silent> K :<C-u>exe("Gtags ".expand('<cword>'))<CR>
    " Show reference of cousor word on quickfix
    nmap <silent> R :<C-u>exe("Gtags -r ".expand('<cword>'))<CR>
'''

[[plugins]]
repo = 'ozelentok/denite-gtags'
hook_add = 'source ~/.config/nvim/bundles/plugins/denite-gtags_settings.vim'

[[plugins]]
repo = 'jsfaint/gen_tags.vim'
hook_add = '''
    let g:gen_tags#gtags_auto_gen = 1
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'source ~/.config/nvim/bundles/plugins/deoplete_settings.vim'
hook_post_source = '''
  let g:deoplete#auto_completion_start_length = 2
'''

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'
hook_add = '''
  let g:LanguageClient_serverCommands = {
    \ 'ruby': ['solargraph', 'stdio'],
    \}
'''

# Syntax checker
[[plugins]]
repo = 'w0rp/ale'
hook_add = 'source ~/.config/nvim/bundles/plugins/ale_settings.vim'

# statusline plugin
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/.config/nvim/bundles/plugins/statusline_settings.vim'

# 非同期処理全般
[[plugins]]
repo = 'Shougo/vimproc.vim'

# colorschema
[[plugins]]
repo = 'chriskempson/vim-tomorrow-theme'
hook_add = 'source ~/.config/nvim/bundles/plugins/vim-tomorrow-theme_settings.vim'

# インデントを可視化
[[plugins]]
repo = 'Yggdroot/indentLine'

# 無駄な空白をハイライト
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# j, k移動高速化
[[plugins]]
repo = 'rhysd/accelerated-jk'
hook_add = 'source ~/.config/nvim/bundles/plugins/accelerated-jk_settings.vim'

# /検索強化
[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = 'source ~/.config/nvim/bundles/plugins/vim-anzu_settings.vim'

# f検索強化
[[plugins]]
repo = 'rhysd/clever-f.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# Auto close parentheses and repeat by dot dot dot...
[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'

# Filer
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = 'source ~/.config/nvim/bundles/plugins/nerdtree_settings.vim'

# "や'などの囲み文字操作
[[plugins]]
repo = 'tpope/vim-surround'

# git
[[plugins]]
repo = "tpope/vim-fugitive"
hook_add = 'source ~/.config/nvim/bundles/plugins/vim-fugitive_settings.vim'

# open github with browser
[[plugins]]
repo = "tpope/vim-rhubarb"
hook_add = 'source ~/.config/nvim/bundles/plugins/vim-rhubarb_settings.vim'

# HEADからの差分を可視化
[[plugins]]
repo = "airblade/vim-gitgutter"

[[plugins]]
repo = "tyru/open-browser.vim"

# Swagger-editor
[[plugins]]
repo = "xavierchow/vim-swagger-preview"

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
 
###fzf.vim
[[plugins]]
repo = 'junegunn/fzf.vim'
